module.exports = {
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  // tutorialSidebar: [
  //   {
  //     type: 'category',
  //     label: 'Getting Started',
  //     items: ['doc1'],
  //   },
  //   {
  //     type: 'category',
  //     label: 'Devices',
  //     items: ['doc2', 'doc3'],
  //   },
  // ],
};
